apiVersion: apps/v1
kind: Deployment
metadata:
  name: backapp
  namespace: {{ .Values.namespace }}
  labels:
    homework: backapp
    training: block4
spec:
  replicas: {{ .Values.backapp.replicas }}
  selector:
    matchLabels:
      app: backapp
  template:
    metadata:
      labels:
        app: backapp
        homework: backapp
        training: block4
    spec:
      containers:
      - name: backapp
        image: {{ .Values.backapp.image }}
        env:
        - name: APP_DEFAULT_MESSAGE
          value: "{{ .Values.backapp.defaultMessage }}"
        - name: JAVA_OPTS
          value: "{{ .Values.backapp.javaOpts }}"
