apiVersion: apps/v1
kind: Deployment
metadata:
  name: backapp
  labels:
    homework: backapp
    training: block4
spec:
  replicas: {{ .Values.backapp.replicas }}
  selector:
    matchLabels:
      app: backapp
  template:
    metadata:
      labels:
        app: backapp
        homework: backapp
        training: block4
    spec:
      containers:
      - name: backapp
        image: {{ required "Name of image is required" .Values.backapp.image }}
        env:
        - name: APP_DEFAULT_MESSAGE
          value: "{{ required "Default message is required" .Values.backapp.defaultMessage }}"
        - name: JAVA_OPTS
          value: "{{ .Values.backapp.javaOpts }}"
        {{- range .Values.backapp.env}}
        - name: {{ .name }} 
          value: {{ .value }} 
        {{- end }}  