apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontapp
  namespace: {{ .Values.namespace }}
  labels:
    homework: frontapp
    training: block4
spec:
  selector:
    matchLabels:
      app: frontapp
  template:
    metadata:
      labels:
        app: frontapp
        homework: frontapp
        training: block4
    spec:
      containers:
      - name: frontapp
        image: {{ required "Name of image is required" .Values.frontapp.image }}
        env:
        - name: BACK_URL
          value: "http://backapp:8080"
        - name: APP_DEFAULT_MESSAGE
          value: "{{ required "Default message is required" .Values.frontapp.defaultMessage }}"
        - name: JAVA_OPTS
          value: "{{ .Values.frontapp.javaOpts }}"
        {{- range .Values.frontapp.env}}
        - name: {{ .name }} 
          value: {{ .value }} 
        {{- end }}
