{{- if .Values.frontapp.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: frontapp
  namespace: {{ .Values.namespace }}
  labels:
    homework: frontapp
    training: block4
spec:
  rules:
  - host: {{ .Values.frontapp.ingress.host }}
    http:
      paths:
      - path: {{ .Values.frontapp.ingress.path }}
        pathType: Prefix
        backend:
          service:
            name: frontapp
            port:
              number: 8080
{{- end }}