apiVersion: v1
kind: Service
metadata:
  name: backapp
  namespace: {{ .Values.namespace }}

  labels:
    homework: backapp
    training: block4
spec:
  selector:
    homework: backapp
    training: block4
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080